### ISSUE TITLE
server error on ignored routes

### ISSUE THREAD

**Issue by rosiecakes** [getgrav/grav-plugin-comments#24]
hi! loving your plugin so far. having a problem with the routes - I copied contents of comments.yaml to my user/config/plugins folder and set an enabled route, and a disabled route. I added the include to my docs template.

when I go to my enabled route it works great! but when I go to any disabled route, either the exact route or its subroute, I get this: 

```
Server Error
Sorry, something went terribly wrong!

400 - Template "partials/comments.html.twig" is not defined in "docs.html.twig" at line 23.

For further details please review your logs/ folder, or enable displaying of errors in your system configuration.
```

this is entered in logs:
```
[2016-05-27 16:18:50] grav.CRITICAL: Template "partials/comments.html.twig" is not defined in "docs.html.twig" at line 23. - Trace: #0 /var/www/html/system/src/Grav/Common/Grav.php(186): Grav\Common\Twig\Twig->processSite(NULL) #1 /var/www/html/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Grav::Grav\Common\{closure}(Object(Grav\Common\Grav)) #2 /var/www/html/system/src/Grav/Common/Grav.php(288): Pimple\Container->offsetGet('output') #3 /var/www/html/index.php(38): Grav\Common\Grav->process() #4 {main} [] []
```

what do you think?

**Comment by flaviocopes** [comment]
Use `{% include 'partials/comments.html.twig' ignore missing %}`

I'll push a code fix to avoid this problem in the first place.
